<?xml version="1.0" encoding="utf-8"?><Database Name="loginDB" Class="loginDBclassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\loginDB.mdf;Integrated Security=True" SettingsObjectName="LoginANDregistationSYSTEM.Properties.Settings" SettingsPropertyName="loginDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>